### ISSUE TITLE
Feeds don't update with LeedSmartFeedsUpdate

### ISSUE THREAD

**Issue by maniackcrudelis** [Simounet/LeedSmartFeedsUpdate#3]
Hello 

I'm using Leed 1.11.0 with the plugin LeedSmartFeedsUpdate 1.0.0 (Up to date with your last commit, I've checked the file `SmartFeedsUpdateFrequencies.php`) and running Leed with php 7.4

Feeds are correctly updated with the synchronization set to "Complete" or "Graduated", but as soon as I set it to "Smart", my feeds stop to update.
When running a manual update with the command `php action.php` I get only the following in my log
```
PHP Notice:  Constant VERSION_NUMBER already defined in /var/www/leed/constant.php on line 2
PHP Notice:  Constant VERSION_NAME already defined in /var/www/leed/constant.php on line 3
```

All slots are empty for Smart feeds update, and the database doesn't have any feeds into leed_plugin_smartfeedsupdate table.

**Comment by Simounet** [comment]
Hi,
Is it a fresh Leed install? Do you have some errors activating the LeedSmartFeedsUpdate's plugin? Can you try to deactivate then activate it again and check at the logs please?

**Comment by maniackcrudelis** [comment]
Hi

That's a pretty old install, several years already.

Deactivating the plugin, I get that:
```
Leed error: Duplicate entry 'synchronisationType' for key 'uniquekey'
PHP message: Leed query: INSERT INTO `leed_configuration`(`id`,`key`,`value`)VALUES('0','synchronisationType','auto');
```
And as well when activating it again
```
Leed error: Duplicate entry 'synchronisationType' for key 'uniquekey'
PHP message: Leed query: INSERT INTO `leed_configuration`(`id`,`key`,`value`)VALUES('0','synchronisationType','smartfeedsupdate');
```

All along, my synchronization was set to 'graduated'.

**Comment by Simounet** [comment]
I made some changes to this plugin. Can you update it and try again, please?

**Comment by maniackcrudelis** [comment]
I've manually updated the files for now.

I no longer have the previous errors when switching on and off the plugin.
And I can see that the feeds have populated the smartFeedsUpdateSettingsBlock page.

For now, I still have no actual update on any feeds, but I'll wait for a few hour to see if it works.

**Comment by maniackcrudelis** [comment]
Everything seems to work perfectly now with your last fix.
Thanks you

**Comment by Simounet** [comment]
Thanks to you for your feedback. Glad to see Leed still being used after all these years.
Have a nice day!
